### ISSUE TITLE
Broke my OS

### ISSUE THREAD

**Issue by matjaz132** [Antergos/nvidia-installer#1]
After running this command I can't boot no more. When that green "OK" text boot finishes it starts to blink. I can't access TTY because it flashes that same text.

How do I fix this? I want to go back to nouveau...

**Comment by karasu** [comment]
Check that you don't have the MODULES="nouveau" line in your mkinitcpio.conf file.

I'll modify the script to check this, too.

**Comment by karasu** [comment]
To go back to nouveau:
`sudo nvidia-installer -n`
