### ISSUE TITLE
GTX 1060 is a supported card

### ISSUE THREAD

**Issue by nikhiljha** [Antergos/nvidia-installer#10]
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] [10de:1c03] (rev a1)

^^

**Comment by karasu** [comment]
Hi,

It's already added to master, but I'm afraid nvidia-installer needs a new release. I'll do it asap.

Thanks!

(I'll leave this open as a reminder)
