### ISSUE TITLE
No suitable driver found for GTX 1060 6GB

### ISSUE THREAD

**Issue by mildlyincompetent** [Antergos/nvidia-installer#11]
Attempting to run nvidia-installer with the card lspci lists as
`22:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] [10de:1c03] (rev a1)`
results in a 
`Couldn't find a driver suitable for your graphics card.`
error.

Using `nvidia-installer -f` appears to work fine however.

**Comment by cupofjoakim** [comment]
I'm in the same boat. Nothing found, but forcing it worked out.

```
[cupofjoakim@antergos ~]$ lspci -k | grep -A 2 -E "(VGA|3D)"
00:02.0 VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)
	Subsystem: Gigabyte Technology Co., Ltd Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller
	Kernel driver in use: i915
--
01:00.0 VGA compatible controller: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] (rev a1)
	Subsystem: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB]
	Kernel driver in use: nouveau
```

**Comment by karasu** [comment]
Added! Thanks both of you.
