### ISSUE TITLE
target not found: bbswitch-lts

### ISSUE THREAD

**Issue by JulioC** [Antergos/nvidia-installer#13]
When trying to run the installer with the bumblebee flag, I get this error message:

> 2018-02-08 14:35:51 [INFO]: Antergos Nvidia Installer v1.13
> 2018-02-08 14:35:51 [INFO]: All logs will be stored in /tmp/nvidia-installer.log
> 2018-02-08 14:35:51 [INFO]: Installing bumblebee driver...
> 2018-02-08 14:35:51 [INFO]: Removing conflicting packages...
> 2018-02-08 14:35:51 [INFO]: Downloading and installing driver packages, please wait...
> 2018-02-08 14:35:52 [ERROR]: Cannot install required packages: :: Synchronizing package databases...
> warning: mesa-17.3.3-2 is up to date -- reinstalling
> warning: lib32-nvidia-utils-390.25-1 is up to date -- reinstalling
> warning: lib32-mesa-17.3.3-1 is up to date -- reinstalling
> warning: nvidia-lts-1:390.25-1 is up to date -- reinstalling
> error: target not found: bbswitch-lts
>  antergos is up to date
>  core is up to date
>  extra is up to date
>  community is up to date
>  multilib is up to date

Looks like this package is only available on AUR

**Comment by JulioC** [comment]
When trying to install it from AUR:

> ==> Install or build missing dependencies for bbswitch-lts:
> error: target not found: linux-lts<4.10
> error: target not found: linux-lts-headers<4.10

**Comment by JulioC** [comment]
After removing `bbswitch-lts` dependency from the installer script, I was able to finish the setup with no errors. I do have bbswitch (from community) installed.

Everything is looking good so far.

**Comment by karasu** [comment]
Thanks for posting your solution. It seems that bbswitch-lts is not packaged anymore ¿? Then if I'm not mistaken,  for lts you must use the dkms version.

Well, I'll remove it from the list as you suggested. Thanks!
