### ISSUE TITLE
latest nvidia package excludes support for cards compatible till 390 version

### ISSUE THREAD

**Issue by killajoe** [Antergos/nvidia-installer#17]
SOURCE: https://github.com/Antergos/antergos-packages/tree/master/antergos/nvidia-installer

DISCUSSION: https://forum.antergos.com/topic/9894/solved-unable-to-load-nvidia-driver

So there are some cards only supported now by 390 legacy driver only, and do not work with latest one
there is a new 390 legacy package:
https://www.archlinux.org/packages/extra/x86_64/nvidia-390xx/
nvidia package will not support some cards anymore...

390 Cards:
http://www.nvidia.com/Download/driverResults.aspx/132530/en-us
396 Cards:
http://www.nvidia.com/Download/driverResults.aspx/133859/en-us

**Comment by karasu** [comment]
https://github.com/Antergos/nvidia-installer/commit/9706f39f12072dd87b17d11c6a35de165cefc59b
