### ISSUE TITLE
Invalid or damaged package (PGP Sign)

### ISSUE THREAD

**Issue by zofiel** [Antergos/nvidia-installer#19]
Antergos standard installation

When I try to install nvidia-installation, I received the error posted on the subject, so i can't install It.

**Comment by karasu** [comment]
Thanks for the warning! Our build server is rebuilding the package. Please bear in mind that it will take a few hours to replicate to all the mirrors.
https://github.com/Antergos/antergos-packages/commit/cd040dc6e20a71cff4dbdbb007c21b1b8a64622f
