### ISSUE TITLE
Can't install driver for GTX1070

### ISSUE THREAD

**Issue by RaccoonTail2** [Antergos/nvidia-installer#3]
Log:
2017-04-19 20:35:22 [INFO]: Antergos Nvidia Installer v1.10
2017-04-19 20:35:22 [INFO]: All logs will be stored in /tmp/nvidia-installer.log
2017-04-19 20:35:22 [ERROR]: Couldn't find a driver suitable for your graphics card.

**Comment by karasu** [comment]
Hi,

Just use the -f parameter, like this:
```
sudo nvidia-installer -f
```

By the way, can you tell us your card id so we can add it to the database? It's shown with
```
lspci -nn | grep VGA
```

Thanks!

**Comment by RaccoonTail2** [comment]
"lspci -nn | grep VGA" output:
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP104 [GeForce GTX 1070] [10de:1b81] (rev a1)

"sudo nvidia-installer -f" work fine)
Thank you.

**Comment by karasu** [comment]
I've updated nvidia-installer with your card info. Thanks!
