### ISSUE TITLE
Can't install driver for gtx 1050ti

### ISSUE THREAD

**Issue by yopspanjers** [Antergos/nvidia-installer#4]
Tried to install nvidia drivers, but it says it can't find suitable drivers.

2017-09-11 20:44:02 [INFO]: Antergos Nvidia Installer v1.12
2017-09-11 20:44:02 [INFO]: All logs will be stored in /tmp/nvidia-installer.log
2017-09-11 20:44:02 [ERROR]: Couldn't find a driver suitable for your graphics card.

**Comment by karasu** [comment]
Can you please put here the result of `sudo lspci -nnn` ? I need your card pci number id.

**Comment by yopspanjers** [comment]
Sure

`00:00.0 Host bridge [0600]: Intel Corporation Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers [8086:5910] (rev 05)
00:01.0 PCI bridge [0604]: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor PCIe Controller (x16) [8086:1901] (rev 05)
00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:591b] (rev 04)
00:14.0 USB controller [0c03]: Intel Corporation Sunrise Point-H USB 3.0 xHCI Controller [8086:a12f] (rev 31)
00:14.2 Signal processing controller [1180]: Intel Corporation Sunrise Point-H Thermal subsystem [8086:a131] (rev 31)
00:16.0 Communication controller [0780]: Intel Corporation Sunrise Point-H CSME HECI #1 [8086:a13a] (rev 31)
00:17.0 SATA controller [0106]: Intel Corporation Sunrise Point-H SATA Controller [AHCI mode] [8086:a103] (rev 31)
00:1c.0 PCI bridge [0604]: Intel Corporation Sunrise Point-H PCI Express Root Port #1 [8086:a110] (rev f1)
00:1c.3 PCI bridge [0604]: Intel Corporation Sunrise Point-H PCI Express Root Port #4 [8086:a113] (rev f1)
00:1c.4 PCI bridge [0604]: Intel Corporation Sunrise Point-H PCI Express Root Port #5 [8086:a114] (rev f1)
00:1f.0 ISA bridge [0601]: Intel Corporation Sunrise Point-H LPC Controller [8086:a152] (rev 31)
00:1f.2 Memory controller [0580]: Intel Corporation Sunrise Point-H PMC [8086:a121] (rev 31)
00:1f.3 Audio device [0403]: Intel Corporation Device [8086:a171] (rev 31)
00:1f.4 SMBus [0c05]: Intel Corporation Sunrise Point-H SMBus [8086:a123] (rev 31)
01:00.0 3D controller [0302]: NVIDIA Corporation GP107M [GeForce GTX 1050 Ti Mobile] [10de:1c8c] (rev a1)
02:00.0 Network controller [0280]: Intel Corporation Device [8086:24fb] (rev 10)
03:00.0 Ethernet controller [0200]: Qualcomm Atheros Device [1969:e0b1] (rev 10)
04:00.0 USB controller [0c03]: ASMedia Technology Inc. ASM1142 USB 3.1 Host Controller [1b21:1242]`

[output.txt](https://github.com/Antergos/nvidia-installer/files/1299391/output.txt)

**Comment by killajoe** [comment]
possible to use the force option, this is what i have to do on my card too..
[nvidia-installer -f]
[sudo lspci -nnn](https://ptpb.pw/mMlh)

**Comment by Firminator** [comment]
1c8c (GTX 1050 Ti Mobile) is missing in the script.
1c82 (GTX 1050 Ti[1] - w/ no 6pin Power connector needed[2]) is also missing.
Will adding these DEVIDs to the NV installer script take care of the installation problem? Or is -f needed?
Which driver version will be installed?

[1] https://pci-ids.ucw.cz/read/PC/10de/1c82
[2] http://wccftech.com/nvidia-geforce-gtx-1050-ti-specs-performance-leak

**Comment by karasu** [comment]
https://github.com/Antergos/nvidia-installer/commit/6d2b09e5eb7158f3da266dcc75f24eaf8fbf9b7e

Now -f will not be necessary. Thanks!

**Comment by sparks305** [comment]
Tried installing drivers for gtx 1050ti today on antergos. 
1. Downloaded nvidia-installer-1.12=-1
2. Performed dry run of installation but got an error (see below).
[john@tower ~]$ nvidia-installer -t
2017-11-25 07:18:59 [INFO]: Antergos Nvidia Installer v1.12
2017-11-25 07:18:59 [INFO]: All logs will be stored in /tmp/nvidia-installer.log
2017-11-25 07:18:59 [INFO]: Running the installer in testing mode...
2017-11-25 07:18:59 [ERROR]: Couldn't find a driver suitable for your graphics card.

Do I need to force it?
