### ISSUE TITLE
Please add my card to working devices list GeForce GT 710B

### ISSUE THREAD

**Issue by killajoe** [Antergos/nvidia-installer#9]
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GK208 [GeForce GT 710B] [10de:128b] (rev a1)

**Comment by karasu** [comment]
Hi,

Is this just working with nvidia or nouveau? Or works with both drivers?

**Comment by killajoe** [comment]
thanks! i just see it is working on a testinstall !
